my:
   greeting: Hello World Trial from config server
   list:
      values: one, two, three, Four

db:
   connection: connection-string-here-from-config-server
   host: 127.0.0.1
   port: 1200